### ISSUE TITLE
RN: Bitrise Cannot find module '../build/cli'

### ISSUE THREAD

**Issue by onmyway133** [onmyway133/notes#359]
```
Run npm command
+ npm test
> FoodshopGuest@0.0.1 test /Users/vagrant/git
> jest
internal/modules/cjs/loader.js:596
    throw err;
    ^
Error: Cannot find module '../build/cli'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/vagrant/git/node_modules/jest/node_modules/jest-cli/bin/jest.js:16:3)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
npm ERR! Test failed.  See above for more details.
|                                                      
```

**Comment by onmyway133** [comment]
https://github.com/facebook/create-react-app/issues/2770
