### ISSUE TITLE
RN: Error: Cannot find module 'jest-haste-map'

### ISSUE THREAD

**Issue by onmyway133** [onmyway133/notes#360]

**Comment by onmyway133** [comment]
`npm install jest-haste-map`

Cannot find module 'jest-worker'

**Comment by onmyway133** [comment]
Cannot find module 'jest-serializer'

**Comment by onmyway133** [comment]
Loading dependency graph...(node:74975) UnhandledPromiseRejectionWarning: Error: `fsevents` unavailable (this watcher can only be used on Darwin)
    at new FSEventsWatcher (/Users/khoa/XcodeProject2/foodshopguest/node_modules/sane/src/fsevents_watcher.js:41:11)
    at createWatcher (/Users/khoa/XcodeProject2/foodshopguest/node_modules/jest-haste-map/build/index.js:780:23)
    at Array.map (<anonymous>)
    at HasteMap._watch (/Users/khoa/XcodeProject2/foodshopguest/node_modules/jest-haste-map/build/index.js:936:44)
    at _buildPromise._buildFileMap.then.then.hasteMap (/Users/khoa/XcodeProject2/foodshopguest/node_modules/jest-haste-map/build/index.js:355:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:74975) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:74975) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by onmyway133** [comment]
Loading dependency graph, done.
error: bundling failed: Error: While trying to resolve module `react-devtools-core` from file
