### ISSUE TITLE
RN: Cannot find module '@babel/core

### ISSUE THREAD

**Issue by onmyway133** [onmyway133/notes#375]
```
/Users/khoa/XcodeProject2/myapp/node_modules/react-native/node_modules/@babel/core/lib/config/full.js:133
    throw e;
    ^

Error: [BABEL] /Users/khoa/XcodeProject2/myapp/node_modules/react-native/local-cli/cliEntry.js: Cannot find module '@babel/core' (While processing: "base$2")
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at _core (/Users/khoa/XcodeProject2/myapp/node_modules/@babel/plugin-proposal-class-properties/lib/index.js:39:16)
    at _default (/Users/khoa/XcodeProject2/myapp/node_modules/@babel/plugin-proposal-class-properties/lib/index.js:64:26)
    at /Users/khoa/XcodeProject2/myapp/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at loadDescriptor (/Users/khoa/XcodeProject2/myapp/node_modules/react-native/node_modules/@babel/core/lib/config/full.js:163:14)
    at cachedFunction (/Users/khoa/XcodeProject2/myapp/node_modules/react-native/node_modules/@babel/core/lib/config/caching.js:42:19)
    at loadPluginDescriptor (/Users/khoa/XcodeProject2/myapp/node_modules/react-native/node_modules/@babel/core/lib/config/full.js:198:28)
```

**Comment by novellizator** [comment]
same error here!

**Comment by Edison4mobile** [comment]
Same

**Comment by krisnailafat** [comment]
any update ?

**Comment by xjrimus** [comment]
same! really need the solution!

**Comment by farshidbakh** [comment]
Any solution on this? I am having the same problem. Thanks.

**Comment by kyniema4** [comment]
i ran: npm install @babel/core
and it work!

**Comment by shiraz27** [comment]
@kyniema4  thank you! it worked.
BUT THEN I HAD TO npm install to fix some problems.
